# Generated by Django 4.0.2 on 2022-02-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_alter_project_image'), ('projects', '0003_alter_project_image'), ('projects', '0004_alter_project_image'), ('projects', '0005_alter_project_image'), ('projects', '0006_alter_project_image'), ('projects', '0007_alter_project_image'), ('projects', '0008_project_slug')]

    initial = True

    dependencies = [
        ('courses', '__first__'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('categories', models.ManyToManyField(to='blog.Category')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
            ],
        ),
    ]
