# Generated by Django 4.0.2 on 2022-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='S:\\OneDrive\\Projects\\afkcode.com\\static/img/'),
        ),
    ]
