# Generated by Django 4.0.2 on 2022-02-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_squashed_0008_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
