# Generated by Django 4.0.3 on 2022-03-08 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_alt_text_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='sorting_priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
