# Generated by Django 4.0.2 on 2022-02-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_projects'),
        ('projects', '0003_remove_project_technology_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
