# Generated by Django 4.0.2 on 2022-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='S:\\OneDrive\\Projects\\afkcode.com\\deployment/media/uploads/'),
        ),
    ]
