# Generated by Django 4.0.2 on 2022-02-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='S:\\OneDrive\\Projects\\afkcode.com\\staticfiles/img/'),
        ),
    ]
