# Generated by Django 4.0.3 on 2022-03-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_user_agent',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
