# Generated by Django 4.0.3 on 2022-03-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_author_ip_comment_author_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
