# Generated by Django 4.0.3 on 2022-03-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_publish_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_ip',
            field=models.GenericIPAddressField(null=True, verbose_name="Author's IP"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_user_agent',
            field=models.CharField(max_length=250, null=True, verbose_name="Author's User-Agent"),
        ),
    ]
