# Generated by Django 4.0.2 on 2022-02-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('courses', '0001_initial'), ('courses', '0002_school_logo'), ('courses', '0003_course_slug')]

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('initials', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('type_letters', models.CharField(blank=True, max_length=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='courses.school')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=5)),
                ('units', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField()),
                ('categories', models.ManyToManyField(to='blog.Category')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.school')),
                ('slug', models.SlugField(default='', editable=False, max_length=25)),
            ],
        ),
    ]
