# Generated by Django 4.0.2 on 2022-02-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
