# Generated by Django 4.0.2 on 2022-02-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_squashed_0003_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
