# Generated by Django 4.0.3 on 2022-03-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_in_progress_alter_course_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Spring A'), (2, 'Spring B'), (3, 'Summer A'), (4, 'Summer B'), (5, 'Fall A'), (6, 'Fall B')], null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
