# Generated by Django 4.0.2 on 2022-02-12 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options'),
        ('courses', '0004_course_completed_course_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='state',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('type_letters', models.CharField(blank=True, max_length=5, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='courses.school')),
            ],
        ),
    ]
