# Generated by Django 4.0.2 on 2022-02-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_school_city_remove_school_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='projects',
        ),
    ]
